[package]
name = "msquic-h3"
version = "0.1.0"
edition = "2021"

[lib]
path = "msquic-h3/src/lib.rs"

[dependencies]
msquic = { version = "2.5.0-beta", path = "./submodules/msquic", default-features = false }
tracing = { version = "0.1", optional = true }
bytes = "1"
h3 = "0.0.7"
futures = { version = "0.3", default-features = false, features = ["std"]}

[features]
# default = ["tracing"]
tracing = ["dep:tracing"]


[dev-dependencies]
http = "1.3"
tokio = {version = "1", features = ["full"]}
tracing-subscriber = "0.3"
tracing = { version = "0.1", features = ["log"] }
msquic = { path = "./submodules/msquic", default-features = false, features = ["find"] }