[package]
name = "simple"
version = "0.1.0"
edition = "2021"
description =  "Example of using the generated MsQuic binding from winmd"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c = { version = "*", path = "../../libs/c", features = ["MsQuic", "Win32_Foundation", "Win32_Networking_WinSock"]}
"windows-core" = "0.56.0"